//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FILM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сеансы.
    /// </summary>
    // *** Start programmer edit section *** (Сеансы CustomAttributes)

    // *** End programmer edit section *** (Сеансы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СеансыE", new string[] {
            "PK as \'PK\'",
            "Код as \'Код\'"})]
    [View("СеансыL", new string[] {
            "PK as \'PK\'",
            "Код as \'Код\'"})]
    public class Сеансы : IIS.FILM.Фильмы
    {
        
        private string fPK;
        
        // *** Start programmer edit section *** (Сеансы CustomMembers)

        // *** End programmer edit section *** (Сеансы CustomMembers)

        
        /// <summary>
        /// PK.
        /// </summary>
        // *** Start programmer edit section *** (Сеансы.PK CustomAttributes)

        // *** End programmer edit section *** (Сеансы.PK CustomAttributes)
        [StrLen(255)]
        public virtual string PK
        {
            get
            {
                // *** Start programmer edit section *** (Сеансы.PK Get start)

                // *** End programmer edit section *** (Сеансы.PK Get start)
                string result = this.fPK;
                // *** Start programmer edit section *** (Сеансы.PK Get end)

                // *** End programmer edit section *** (Сеансы.PK Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сеансы.PK Set start)

                // *** End programmer edit section *** (Сеансы.PK Set start)
                this.fPK = value;
                // *** Start programmer edit section *** (Сеансы.PK Set end)

                // *** End programmer edit section *** (Сеансы.PK Set end)
            }
        }
        
        // *** Start programmer edit section *** (Сеансы.FLOAT CustomAttributes)

        // *** End programmer edit section *** (Сеансы.FLOAT CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void FLOAT()
        {
            // *** Start programmer edit section *** (Сеансы.FLOAT method implementation)

            return;
            // *** End programmer edit section *** (Сеансы.FLOAT method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СеансыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СеансыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СеансыE", typeof(IIS.FILM.Сеансы));
                }
            }
            
            /// <summary>
            /// "СеансыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СеансыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СеансыL", typeof(IIS.FILM.Сеансы));
                }
            }
        }
    }
}
